### ISSUE TITLE
cf-operator crashes on first run

### ISSUE THREAD

**Issue by f0rmiga** [cloudfoundry-incubator/cf-operator#730] opened 2019-12-02 20:03 UTC
It fails with:
```
2019/12/02 20:01:00 cf-operator command failed. Failed to create new manager.: failed to add controllers to manager: no matches for kind "ExtendedStatefulSet" in version "quarks.cloudfoundry.org/v1alpha1"
```

**Comment by rohitsakala** [comment] 2019-12-05 12:12
Hi @f0rmiga ,

I tried to reproduce this on latest master in `cf-operator`. Steps I tried

1. Deleted my kind clusters
2. Created a new kind cluster.
3. Ran `go run ./cmd/cf-operator/main.go
4. and there was no error as above.

Am I missing anything ?

**Comment by f0rmiga** [comment] 2019-12-05 17:17
@rohitsakala Try deploying the helm chart.

**Comment by rohitsakala** [comment] 2019-12-05 23:28
Ran deploying using helm chart for 10 times in a loop. Couldn't reproduce. @f0rmiga to provide more info if seen again.

**Comment by manno** [comment] 2019-12-13 10:06
I'm going to close the issue. If this happens again, @f0rmiga please re-open and add more information on how to reproduce it: 
Which commands did you run, what's kind of Kubernetes cluster are you using, what version of the helm chart was used, etc.

**Closed by manno** 2019-12-13 10:06 UTC
Labels: bug, in progress
