### ISSUE TITLE
Links with long names generate incorrect secret names

### ISSUE THREAD

**Issue by mook-as** [cloudfoundry-incubator/cf-operator#826] opened 2020-02-21 19:40 UTC
BOSH links with very long names result in incorrectly named secrets.

I have a BOSH link that has a long name (type: `cloud-controller-https-endpoint`, name: `cloud-controller-https-endpoint`).  When attempting to use it as a link via a non-BOSH pod, things break down because the secret is named incorrectly.

In the instance group resolver, the link is saved with the sanitized name: [`InstanceGroupResolver.SaveLinks()`]  At this point it's something like `cloud-controller-https-endpoint-cloud-controller-https-endpoint`, which is under the 64 character limit (it's exactly 63 characters long…)

Once that is saved in the JSON file, the output persistor then converts it into a Kube secret in [`OutputPersistor.persistContainer()`], adding a `link-<deployment>` prefix, which pushes it over the character limit.  Kube appears to have no issues with this at all; it just creates a secret named `link-kubecf-cloud-controller-https-endpoint-cloud-controller-https-endpoint`.

However, when I actually try to use this link, [`entanglement.find()`] builds the whole secret name, and then correctly sanitizes it into `link-kubecf-cloud-controller-ht25a2babe3b153705e99759ccaa08e894`, which is of course missing.

For further confirmation, I also appear to have a secret named `link-kubecf-cloud-controller-container-netwca5e01c51356109485f319b42a7b9bfa` (where the part without the `link-kubecf-` prefix is 63 characters long), from a link of type and name `cloud_controller_container_networking_info`.

I believe the fix is to stop sanitizing at [`InstanceGroupResolver.SaveLinks()`] and sanitize at [`OutputPersistor.persistContainer()`] instead.  As that's cross-repo and I'm not sure how to handle that, I'll not provide a PR (though that fix appears to work locally).

[`InstanceGroupResolver.SaveLinks()`]: https://github.com/cloudfoundry-incubator/cf-operator/blob/53333950a93e33048c18ff227baf2309a441b7b7/pkg/bosh/manifest/cmd_instance_group_resolver.go#L162
[`OutputPersistor.persistContainer()`]:https://github.com/cloudfoundry-incubator/quarks-job/blob/d8d4a91eb6639fada0e77116d3b45dfe02a75b09/pkg/kube/controllers/quarksjob/output_persistor.go#L145
[`entanglement.find()`]: https://github.com/cloudfoundry-incubator/cf-operator/blob/53333950a93e33048c18ff227baf2309a441b7b7/pkg/kube/controllers/quarkslink/entanglement.go#L95

**Comment by manno** [comment] 2020-02-24 12:51
If I understand correctly the problem is that the generated link is not found. So this bug should be fixed by implementing https://www.pivotaltracker.com/story/show/171433464

**Closed** 2020-03-10 17:02 UTC
Labels: accepted
