### ISSUE TITLE
cf-operator 0.4.2 + scfv3, not generating one secret

### ISSUE THREAD

**Issue by cloudziu** [cloudfoundry-incubator/cf-operator#648] opened 2019-10-16 07:23 UTC
Version of cf-operator: **cf-operator-v0.4.2+0.g604925f0.tgz**
Version of scf v3: **scf-3.0.0-8f7a71d1.tgz** + build from **/SUSE/scf/tree/v3-develop**

While deploying SCFv3 there should be created a secret in eirini namespace: **eirini-staging-secret**
I think that this is be done by the **scf-configure-eirini-0a5ff711ba35c6d2-llm9d** pod.
I could not get any log from it because it spin up and down immediately. Other secrets in scf namespace are generating properly. 

```
$ kubectl get -n scf-eirini secrets
NAME                  TYPE                                  DATA   AGE
default-token-mmsl4   kubernetes.io/service-account-token   3      11m

$ kubectl get -n scf secrets
NAME                                                          TYPE                                  DATA   AGE
cf-operator-token-9w666                                       kubernetes.io/service-account-token   3      14m
cf-operator-webhook-server-cert                               Opaque                                4      14m
default-token-bf65q                                           kubernetes.io/service-account-token   3      14m
persist-output-service-account-token-8f72v                    kubernetes.io/service-account-token   3      11m
scf-eirini-token-2t7lk                                        kubernetes.io/service-account-token   3      11m
scf.bpm.adapter-v1                                            Opaque                                1      8m51s
scf.bpm.api-v1                                                Opaque                                1      8m44s
scf.bpm.bits-v1                                               Opaque                                1      8m48s
scf.bpm.cc-worker-v1                                          Opaque                                1      8m49s
scf.bpm.configure-eirini-v1                                   Opaque                                1      8m50s
scf.bpm.database-v1                                           Opaque                                1      8m51s
scf.bpm.diego-api-v1                                          Opaque                                1      8m50s
scf.bpm.doppler-v1                                            Opaque                                1      8m45s
scf.bpm.eirini-v1                                             Opaque                                1      8m46s
scf.bpm.log-api-v1                                            Opaque                                1      8m46s
scf.bpm.nats-v1                                               Opaque                                1      8m51s
scf.bpm.router-v1                                             Opaque                                1      8m47s
scf.bpm.scheduler-v1                                          Opaque                                1      8m46s
scf.bpm.singleton-blobstore-v1                                Opaque                                1      8m49s
scf.bpm.uaa-v1                                                Opaque                                1      8m50s
scf.desired-manifest-v1                                       Opaque                                1      9m28s
scf.ig-resolved.adapter-v1                                    Opaque                                1      8m51s
scf.ig-resolved.adapter-v2                                    Opaque                                1      8m46s
scf.ig-resolved.api-v1                                        Opaque                                1      8m40s
scf.ig-resolved.bits-v1                                       Opaque                                1      8m42s
scf.ig-resolved.cc-worker-v1                                  Opaque                                1      8m44s
scf.ig-resolved.configure-eirini-v1                           Opaque                                1      8m43s
scf.ig-resolved.database-v1                                   Opaque                                1      8m50s
scf.ig-resolved.database-v2                                   Opaque                                1      8m45s
scf.ig-resolved.diego-api-v1                                  Opaque                                1      8m45s
scf.ig-resolved.doppler-v1                                    Opaque                                1      8m40s
scf.ig-resolved.eirini-v1                                     Opaque                                1      8m41s
scf.ig-resolved.log-api-v1                                    Opaque                                1      8m41s
scf.ig-resolved.nats-v1                                       Opaque                                1      8m51s
scf.ig-resolved.nats-v2                                       Opaque                                1      8m47s
scf.ig-resolved.router-v1                                     Opaque                                1      8m42s
scf.ig-resolved.scheduler-v1                                  Opaque                                1      8m40s
scf.ig-resolved.singleton-blobstore-v1                        Opaque                                1      8m43s
scf.ig-resolved.uaa-v1                                        Opaque                                1      8m42s
scf.var-adapter-rlp-tls                                       Opaque                                4      10m
scf.var-adapter-tls                                           Opaque                                4      10m
scf.var-application-ca                                        Opaque                                3      10m
scf.var-bits-service-secret                                   Opaque                                1      10m
scf.var-bits-service-signing-password                         Opaque                                1      10m
scf.var-bits-service-ssl                                      Opaque                                3      10m
scf.var-blobstore-admin-users-password                        Opaque                                1      11m
scf.var-blobstore-secure-link-secret                          Opaque                                1      11m
scf.var-blobstore-tls                                         Opaque                                4      10m
scf.var-cc-bridge-cc-uploader                                 Opaque                                4      10m
scf.var-cc-bridge-cc-uploader-server                          Opaque                                4      10m
scf.var-cc-bridge-tps                                         Opaque                                4      10m
scf.var-cc-bulk-api-password                                  Opaque                                1      11m
scf.var-cc-database-password                                  Opaque                                1      11m
scf.var-cc-db-encryption-key                                  Opaque                                1      11m
scf.var-cc-internal-api-password                              Opaque                                1      11m
scf.var-cc-logcache-tls                                       Opaque                                4      10m
scf.var-cc-public-tls                                         Opaque                                4      10m
scf.var-cc-staging-upload-password                            Opaque                                1      11m
scf.var-cc-tls                                                Opaque                                4      10m
scf.var-cf-admin-password                                     Opaque                                1      11m
scf.var-cf-bosh-password                                      Opaque                                1      11m
scf.var-cf-mysql-mysql-admin-password                         Opaque                                1      11m
scf.var-cf-mysql-mysql-cluster-health-password                Opaque                                1      11m
scf.var-cf-mysql-mysql-galera-healthcheck-endpoint-password   Opaque                                1      11m
scf.var-cf-mysql-mysql-galera-healthcheck-password            Opaque                                1      11m
scf.var-cf-mysql-proxy-api-password                           Opaque                                1      11m
scf.var-credhub-admin-client-secret                           Opaque                                1      11m
scf.var-credhub-ca                                            Opaque                                3      10m
scf.var-credhub-database-password                             Opaque                                1      11m
scf.var-deployment-name                                       Opaque                                1      11m
scf.var-diego-auctioneer-client                               Opaque                                4      10m
scf.var-diego-auctioneer-server                               Opaque                                4      10m
scf.var-diego-bbs-client                                      Opaque                                4      10m
scf.var-diego-bbs-encryption-keys-passphrase                  Opaque                                1      11m
scf.var-diego-bbs-server                                      Opaque                                4      10m
scf.var-diego-database-password                               Opaque                                1      11m
scf.var-diego-instance-identity-ca                            Opaque                                3      10m
scf.var-diego-locket-client                                   Opaque                                4      10m
scf.var-diego-locket-server                                   Opaque                                4      10m
scf.var-diego-rep-agent-v2                                    Opaque                                4      10m
scf.var-diego-rep-client                                      Opaque                                4      10m
scf.var-diego-ssh-proxy-host-key                              Opaque                                3      10m
scf.var-expvar-forwarder                                      Opaque                                4      10m
scf.var-gorouter-backend-tls                                  Opaque                                4      10m
scf.var-k8s-host-url                                          Opaque                                1      11m
scf.var-k8s-node-ca                                           Opaque                                1      11m
scf.var-k8s-service-token                                     Opaque                                1      11m
scf.var-k8s-service-username                                  Opaque                                1      11m
scf.var-locket-database-password                              Opaque                                1      10m
scf.var-log-cache                                             Opaque                                4      10m
scf.var-log-cache-ca                                          Opaque                                3      10m
scf.var-log-cache-to-loggregator-agent                        Opaque                                4      10m
scf.var-logcache-ssl                                          Opaque                                4      10m
scf.var-loggregator-ca                                        Opaque                                3      10m
scf.var-loggregator-rlp-gateway                               Opaque                                4      10m
scf.var-loggregator-rlp-gateway-tls                           Opaque                                4      10m
scf.var-loggregator-rlp-gateway-tls-cc                        Opaque                                4      10m
scf.var-loggregator-tls-agent                                 Opaque                                4      10m
scf.var-loggregator-tls-cc-tc                                 Opaque                                4      10m
scf.var-loggregator-tls-doppler                               Opaque                                4      10m
scf.var-loggregator-tls-rlp                                   Opaque                                4      10m
scf.var-loggregator-tls-statsdinjector                        Opaque                                4      10m
scf.var-loggregator-tls-tc                                    Opaque                                4      10m
scf.var-loggregator-trafficcontroller-tls                     Opaque                                4      10m
scf.var-logs-provider                                         Opaque                                4      10m
scf.var-mysql-server-certificate                              Opaque                                4      10m
scf.var-nats-password                                         Opaque                                1      11m
scf.var-network-connectivity-database-password                Opaque                                1      11m
scf.var-network-policy-ca                                     Opaque                                3      11m
scf.var-network-policy-client                                 Opaque                                4      11m
scf.var-network-policy-database-password                      Opaque                                1      11m
scf.var-network-policy-server                                 Opaque                                4      11m
scf.var-pxc-server-ca                                         Opaque                                3      10m
scf.var-releases-defaults-url                                 Opaque                                1      11m
scf.var-router-ca                                             Opaque                                3      10m
scf.var-router-route-services-secret                          Opaque                                1      11m
scf.var-router-ssl                                            Opaque                                4      10m
scf.var-router-status-password                                Opaque                                1      11m
scf.var-routing-api-database-password                         Opaque                                1      11m
scf.var-scheduler-api-tls                                     Opaque                                4      10m
scf.var-scheduler-client-tls                                  Opaque                                4      10m
scf.var-service-cf-internal-ca                                Opaque                                3      10m
scf.var-ssh-proxy-backends-tls                                Opaque                                4      9m57s
scf.var-system-domain                                         Opaque                                1      11m
scf.var-uaa-admin-client-secret                               Opaque                                1      11m
scf.var-uaa-ca                                                Opaque                                3      10m
scf.var-uaa-clients-cc-routing-secret                         Opaque                                1      11m
scf.var-uaa-clients-cc-service-dashboards-secret              Opaque                                1      11m
scf.var-uaa-clients-cc-service-key-client-secret              Opaque                                1      11m
scf.var-uaa-clients-cf-smoke-tests-secret                     Opaque                                1      11m
scf.var-uaa-clients-cloud-controller-username-lookup-secret   Opaque                                1      11m
scf.var-uaa-clients-doppler-secret                            Opaque                                1      11m
scf.var-uaa-clients-gorouter-secret                           Opaque                                1      11m
scf.var-uaa-clients-network-policy-secret                     Opaque                                1      11m
scf.var-uaa-clients-routing-api-client-secret                 Opaque                                1      11m
scf.var-uaa-clients-ssh-proxy-secret                          Opaque                                1      11m
scf.var-uaa-clients-tcp-emitter-secret                        Opaque                                1      11m
scf.var-uaa-clients-tcp-router-secret                         Opaque                                1      11m
scf.var-uaa-database-password                                 Opaque                                1      11m
scf.var-uaa-default-encryption-passphrase                     Opaque                                1      11m
scf.var-uaa-jwt-signing-key                                   Opaque                                2      10m
scf.var-uaa-login-saml                                        Opaque                                4      9m57s
scf.var-uaa-ssl                                               Opaque                                4      9m56s
scf.with-ops                                                  Opaque                                1      11m
```
To resolve this problem I had to use the older cf-operator (cf-operator-v0.4.1+38.g96b7709a.tgz) . In both cases ( using the older scfv3 chart and using the built one from v3-develop) it generate properly the eirini-staging-secret.
```
$ kubectl get -n scf-eirini secrets
NAME                    TYPE                                  DATA   AGE
default-token-hftkt     kubernetes.io/service-account-token   3      42h
eirini-staging-secret   Opaque                                5      42h
```

**Comment by f0rmiga** [comment] 2019-10-23 07:46
This was caused by a bug on the extended job that was not passing down the specified service account to the pod. It was fixed in https://github.com/cloudfoundry-incubator/quarks-job/pull/12 and integrated with cf-operator in https://github.com/cloudfoundry-incubator/cf-operator/pull/656.

**Closed by f0rmiga** 2019-10-23 07:46 UTC
Labels: unscheduled
